/* eslint-disable import/extensions */
import * as assert from 'assert';
import convert from '../dist/main.js';

it('JS', () => {
  assert.strictEqual(
    convert({ intValue: -12, strValue: 'haha"\'', nullValue: null, arrayValue: [32, 'wow', null] }),
    `/* eslint-disable */

/******************************************************************************************
* This code was automatically generated by json-to-js-const.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

export const intValue = -12;
export const strValue = "haha\\"'";
export const nullValue = null;
export const arrayValue = [32,"wow",null];
`,
  );
});

it('Typescript definition', () => {
  assert.strictEqual(
    convert(
      {
        intValue: -12,
        strValue: 'haha"\'',
        nullValue: null,
        intArr: [1, 2],
        strArr: ['a', 'b'],
      },
      true,
    ),
    `/* eslint-disable */

/******************************************************************************************
* This code was automatically generated by json-to-js-const.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

export declare const intValue = -12;
export declare const strValue = "haha\\"'";
export declare const nullValue = null;
export declare const intArr: number[];
export declare const strArr: string[];
`,
  );
});
