const defaultHeader = `/* eslint-disable */

/******************************************************************************************
* This code was automatically generated by json-to-js-const.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

`;

export interface Options {
  // TypeScript definition mode.
  dts?: boolean;
  // Allows an extra string inserted at the top of output file.
  header?: string;
}

function getTail(val: unknown, dts: boolean | undefined) {
  if (dts && Array.isArray(val)) {
    return `: ${typeof val[0]}[]`;
  }
  return ` = ${JSON.stringify(val)}`;
}

export default function convert(obj: Record<string, unknown>, opt?: Options): string {
  let result = `${opt?.header ?? ''}${defaultHeader}`;
  for (const [key, val] of Object.entries(obj)) {
    result += `export${opt?.dts ? ' declare' : ''} const ${key}${getTail(val, opt?.dts)};\n`;
  }
  return result;
}
