const defaultHeader = `/******************************************************************************************
* This code was automatically generated by json-to-js-const.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

`;

export default function convert(obj: Record<string, unknown>): string {
  let result = defaultHeader;
  for (const [key, val] of Object.entries(obj)) {
    result += `export const ${key} = ${JSON.stringify(val)};\n`;
  }
  return result;
}
